### ISSUE TITLE
Remove base_footprint from URDF

### ISSUE THREAD

**Issue by mikepurvis** [husky/husky_description#6]
For compliance with [REP-105](http://www.ros.org/reps/rep-0105.html), I believe that `base_footprint`, if present at all, should be a child of `base_link`, and probably should be dynamically published by something that's aware of the platform's attitude.

This change should happen for Indigo, but it's also more immediately needed for Husky units equipped with integrated INS systems, as those systems publish an `odom -> base_link` transform.

@pmukherj, @y22ma, @rgariepy: This make sense to you guys? What are the implications to navigation?

**Comment by rgariepy** [comment]
I would be in favour of removing base_footprint altogether.

-R

**Comment by mikepurvis** [comment]
Closed via 1fbe4df9a87376520eec16b769cad378fb6bc703
